const IM_TYPE_DIALOG = 'dialog_submission'
const IM_TYPE_INTERACTIVE_MSG = 'interactive_message'
const IM_MSG_TYPE_CURRENT_GOAL = 'select_current_goal'
const IM_MSG_TYPE_SELECT_OR_CREATE  = 'select_or_create_goal'
const IM_MSG_TYPE_STATUS_UPDATE = 'unleash_status_update'
const IM_MSG_TYPE_CREATE_FIRST_GOAL = 'create_first_goal'
const IM_MSG_TYPE_AFTER_GOAL_CREATED = 'post_goal_created'
const IM_MSG_TYPE_AFTER_GOAL_SWITCHED = 'post_goal_switched'
const DEFAULT_GOAL_LVL = 1
const DEFAULT_GOAL_ICON = 'home'
const IM_MENU_TYPE = 'select'
const IM_BUTTON_TYPE = 'button'
const MKTHX = 'Ok, thx!'
const ACTION_GOAL_COMPLETED = 1
const ACTION_MORE_TIME = 0
const ACTION_SET_GOAL_IN_PROGRESS = 'in_progress'
const ACTION_CREATE_NEW_GOAL = 'create_new'
const ATTCH_MSG_GOAL_COMPLETED = 'goal_completed'
const GENERIC_NO = 'no'
const GENERIC_YES = 'yes'

export {
  IM_TYPE_DIALOG,
  IM_TYPE_INTERACTIVE_MSG,
  IM_MSG_TYPE_CURRENT_GOAL,
  IM_MSG_TYPE_SELECT_OR_CREATE ,
  IM_MSG_TYPE_STATUS_UPDATE,
  IM_MSG_TYPE_CREATE_FIRST_GOAL,
  IM_MSG_TYPE_AFTER_GOAL_CREATED,
  IM_MSG_TYPE_AFTER_GOAL_SWITCHED,
  DEFAULT_GOAL_LVL,
  DEFAULT_GOAL_ICON,
  IM_MENU_TYPE,
  IM_BUTTON_TYPE,
  MKTHX,
  ACTION_GOAL_COMPLETED,
  ACTION_MORE_TIME,
  ACTION_SET_GOAL_IN_PROGRESS,
  ACTION_CREATE_NEW_GOAL,
  ATTCH_MSG_GOAL_COMPLETED,
  GENERIC_NO,
  GENERIC_YES
}
